### ISSUE TITLE
Typo in translation

### ISSUE THREAD

**Issue by mu4ddi3** [kacskrz/xiaomi.eu_PL_V14#1]
https://github.com/kacskrz/xiaomi.eu_PL_V14/blob/e56f3ab08df2a0209e8ba29e95c83eeb99058f43/Polish/main/Notes.apk/res/values-pl/strings.xml#L85

**Comment by kacskrz** [comment]
Fixed

**Comment by mu4ddi3** [comment]
thx, kudos for great job
