### ISSUE TITLE
Problems with connection

### ISSUE THREAD

**Issue by mixmint** [kacskrz/xiaomi.eu_PL_V14#2]
Podczas rozmów telefonicznych zrywane są połączenia - zwykle po 10 sekundach, czasem jest to dłużej (około 30 sekund) oraz nie za każdym razem się to zdarza

Nie można połączyć się ze słuchawkami bluetooth, słuchawki które były sparowane nawiązując połączenie z telefonem natychmiast się wyłączają. Gdy się je paruje ponownie, przechodzą ten proces poprawnie lecz po nawiązaniu właściwego połączenia znów się wyłączają. Bardzo trudno je sparować gdy włączone jest "Sparuj kompatybilne urządzenia"

**Comment by kacskrz** [comment]
OK, ale
1. Nie wiadomo o jakim modelu piszesz
2. Na Bluetooth nie mamy wielkiego wpływu
3. Takie sprawy na forum miuipolska lub xiaomi.eu
4. Sekcja Issues tutaj służy tylko do zgłaszania problemów z tłumaczeniem, a nie z ROM-em
